address_book/address_book/config/routes.rb
AddressBook::Application.routes.draw do
  resources :users
  resources :addresses

end

address_book/address_book/app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  attr_accessible :city, :state, :street, :zip, :user_id
  validates :city, :state, :street, :zip, :user_id, presence: true

  validates_format_of :zip,
                      :with => %r{\d{5}},
                      :message => "Zip Code should be a number"

  validates_format_of :state,
                      :with => %r{[A-Z]{2}},
                      :message => "State should be a two letter abbreviation"

  validates_format_of :state,
                      :with => %r{/AK|AZ|CT|FL|HI|IL|KY|MD|MN|MT|NE|NM|OH|PA|SC|TX|VI|WI|AL|CA|DC|GA|IA|IN|LA|ME|MO|NC|NH|NV|OK|PR|SD|UT|VT|WV|AR|CO|DE|GU|ID|KS|MA|MI|MS|ND|NJ|NY|OR|RI|TN|VA|WA|WY/},
                      :message => "Must be a valid state"

  #scope :by_state (state)

end

address_book/address_book/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  validates :first_name, :last_name, presence: true
  has_many :addresses, :dependent => :destroy

  def full_name
    self.first_name + " " + self.last_name
  end
end

address_book/address_book/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

address_book/address_book/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

address_book/address_book/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    if @user.persisted?
      redirect_to user_path(@user.id)
    else
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

address_book/address_book/app/helpers/addresses_helper.rb
module AddressesHelper
end

address_book/address_book/app/helpers/application_helper.rb
module ApplicationHelper
end

address_book/address_book/app/helpers/users_helper.rb
module UsersHelper
end

address_book/address_book/app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :street %>
      <%= f.text_field :street %>
    </p>

    <p>
      <%= f.label :zip %>
      <%= f.text_field :zip %>
    </p>

    <p>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </p>

    <p>
      <%= f.label :state %>
      <%= f.text_field :state %>
    </p>

    <p>
      <%= f.label :user_id %>
      <%= f.select(:user_id, options_from_collection_for_select(User.all, :id, :full_name, @address.user_id)) %>
    </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

address_book/address_book/app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

address_book/address_book/app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>User ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.street %></td>
    <td><%= address.city %></td>
    <td><%= address.state %></td>
    <td><%= address.zip %></td>
    <td><%= address.user_id %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

address_book/address_book/app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

address_book/address_book/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
    <%= @address.user.full_name %><br />
    <%= @address.street %><br />
    <%= @address.city %>, <%= @address.state %> <%= @address.zip %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

address_book/address_book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



</body>
</html>

address_book/address_book/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |f| %>
    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
      <%= @user.errors[:first_name] %>
    </p>

    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
      <%= @user.errors[:last_name] %>
    </p>

    <%= f.submit %>
<% end %>

address_book/address_book/app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><a href="/users/<%= user.id %>"><%= "#{user.first_name} #{user.last_name}" %></a> <a href="/users/<%= user.id %>/edit/">Edit</a></li>
  <% end %>
</ul>

address_book/address_book/app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
    <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= @user.errors[:first_name] %>
    </p>

    <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= @user.errors[:first_name] %>
    </p>

    <%= f.submit %>
<% end %>

address_book/address_book/app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<a href="/users/<%= @user.id %>/edit/">Edit</a>